"Name: \PR:ZHRPY_TIMESHEET_UPLOAD\FO:CHECK_RFC_IMPLEMENTED\SE:END\EI
ENHANCEMENT 0 ZHRAUPY_EI_PCC_TS_UPLOAD.
 MOVE 15 TO lv_rfc_jobs.
 MOVE lv_rfc_jobs             TO gs_control-wps_number.
ENDENHANCEMENT.
