*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZHRPY_PCC_VTXKEY................................*
FORM GET_DATA_ZHRPY_PCC_VTXKEY.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZHRPY_PCC_TXTKEY WHERE
(VIM_WHERETAB) .
    CLEAR ZHRPY_PCC_VTXKEY .
ZHRPY_PCC_VTXKEY-MANDT =
ZHRPY_PCC_TXTKEY-MANDT .
ZHRPY_PCC_VTXKEY-PROCESS_TEMPLATE =
ZHRPY_PCC_TXTKEY-PROCESS_TEMPLATE .
ZHRPY_PCC_VTXKEY-STEP_TEMPLATE =
ZHRPY_PCC_TXTKEY-STEP_TEMPLATE .
    SELECT SINGLE * FROM PYD_D_CLST WHERE
SPRSL = 'E' AND
ID = ZHRPY_PCC_TXTKEY-PROCESS_TEMPLATE .
    IF SY-SUBRC EQ 0.
ZHRPY_PCC_VTXKEY-PNAME =
PYD_D_CLST-NAME .
    ENDIF.
    SELECT SINGLE * FROM PYD_D_TYT WHERE
SPRSL = 'E' AND
TYPE = ZHRPY_PCC_TXTKEY-STEP_TEMPLATE .
    IF SY-SUBRC EQ 0.
ZHRPY_PCC_VTXKEY-SNAME =
PYD_D_TYT-NAME .
    ENDIF.
<VIM_TOTAL_STRUC> = ZHRPY_PCC_VTXKEY.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZHRPY_PCC_VTXKEY .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZHRPY_PCC_VTXKEY.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZHRPY_PCC_VTXKEY-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZHRPY_PCC_TXTKEY WHERE
  PROCESS_TEMPLATE = ZHRPY_PCC_VTXKEY-PROCESS_TEMPLATE AND
  STEP_TEMPLATE = ZHRPY_PCC_VTXKEY-STEP_TEMPLATE .
    IF SY-SUBRC = 0.
    DELETE ZHRPY_PCC_TXTKEY .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZHRPY_PCC_TXTKEY WHERE
  PROCESS_TEMPLATE = ZHRPY_PCC_VTXKEY-PROCESS_TEMPLATE AND
  STEP_TEMPLATE = ZHRPY_PCC_VTXKEY-STEP_TEMPLATE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZHRPY_PCC_TXTKEY.
    ENDIF.
ZHRPY_PCC_TXTKEY-MANDT =
ZHRPY_PCC_VTXKEY-MANDT .
ZHRPY_PCC_TXTKEY-PROCESS_TEMPLATE =
ZHRPY_PCC_VTXKEY-PROCESS_TEMPLATE .
ZHRPY_PCC_TXTKEY-STEP_TEMPLATE =
ZHRPY_PCC_VTXKEY-STEP_TEMPLATE .
    IF SY-SUBRC = 0.
    UPDATE ZHRPY_PCC_TXTKEY ##WARN_OK.
    ELSE.
    INSERT ZHRPY_PCC_TXTKEY .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZHRPY_PCC_VTXKEY-UPD_FLAG,
STATUS_ZHRPY_PCC_VTXKEY-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZHRPY_PCC_VTXKEY.
  SELECT SINGLE * FROM ZHRPY_PCC_TXTKEY WHERE
PROCESS_TEMPLATE = ZHRPY_PCC_VTXKEY-PROCESS_TEMPLATE AND
STEP_TEMPLATE = ZHRPY_PCC_VTXKEY-STEP_TEMPLATE .
ZHRPY_PCC_VTXKEY-MANDT =
ZHRPY_PCC_TXTKEY-MANDT .
ZHRPY_PCC_VTXKEY-PROCESS_TEMPLATE =
ZHRPY_PCC_TXTKEY-PROCESS_TEMPLATE .
ZHRPY_PCC_VTXKEY-STEP_TEMPLATE =
ZHRPY_PCC_TXTKEY-STEP_TEMPLATE .
    SELECT SINGLE * FROM PYD_D_CLST WHERE
SPRSL = 'E' AND
ID = ZHRPY_PCC_TXTKEY-PROCESS_TEMPLATE .
    IF SY-SUBRC EQ 0.
ZHRPY_PCC_VTXKEY-PNAME =
PYD_D_CLST-NAME .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHRPY_PCC_VTXKEY-PNAME .
    ENDIF.
    SELECT SINGLE * FROM PYD_D_TYT WHERE
SPRSL = 'E' AND
TYPE = ZHRPY_PCC_TXTKEY-STEP_TEMPLATE .
    IF SY-SUBRC EQ 0.
ZHRPY_PCC_VTXKEY-SNAME =
PYD_D_TYT-NAME .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHRPY_PCC_VTXKEY-SNAME .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZHRPY_PCC_VTXKEY USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZHRPY_PCC_VTXKEY-PROCESS_TEMPLATE TO
ZHRPY_PCC_TXTKEY-PROCESS_TEMPLATE .
MOVE ZHRPY_PCC_VTXKEY-STEP_TEMPLATE TO
ZHRPY_PCC_TXTKEY-STEP_TEMPLATE .
MOVE ZHRPY_PCC_VTXKEY-MANDT TO
ZHRPY_PCC_TXTKEY-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZHRPY_PCC_TXTKEY'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZHRPY_PCC_TXTKEY TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZHRPY_PCC_TXTKEY'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZHRPY_PCC_VTXKEY USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZHRPY_PCC_TXTKEY-MANDT =
ZHRPY_PCC_VTXKEY-MANDT .
ZHRPY_PCC_TXTKEY-PROCESS_TEMPLATE =
ZHRPY_PCC_VTXKEY-PROCESS_TEMPLATE .
ZHRPY_PCC_TXTKEY-STEP_TEMPLATE =
ZHRPY_PCC_VTXKEY-STEP_TEMPLATE .
    SELECT SINGLE * FROM PYD_D_CLST WHERE
SPRSL = 'E' AND
ID = ZHRPY_PCC_TXTKEY-PROCESS_TEMPLATE .
    IF SY-SUBRC EQ 0.
ZHRPY_PCC_VTXKEY-PNAME =
PYD_D_CLST-NAME .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHRPY_PCC_VTXKEY-PNAME .
    ENDIF.
    SELECT SINGLE * FROM PYD_D_TYT WHERE
SPRSL = 'E' AND
TYPE = ZHRPY_PCC_TXTKEY-STEP_TEMPLATE .
    IF SY-SUBRC EQ 0.
ZHRPY_PCC_VTXKEY-SNAME =
PYD_D_TYT-NAME .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHRPY_PCC_VTXKEY-SNAME .
    ENDIF.
ENDFORM.
